fix runner spec for llvm windows build

diff --git a/.github/workflows/build-llvm-windows.yaml b/.github/workflows/build-llvm-windows.yaml
--- a/.github/workflows/build-llvm-windows.yaml
+++ b/.github/workflows/build-llvm-windows.yaml
@@ -6,10 +6,16 @@ on: workflow_dispatch
 jobs:
   build-llvm-windows:
     name: "Build LLVM x86_64-unknown-windows-msvc"
-    runs-on:
-      - windows-2022
-      - x64
+    runs-on: windows-2022
     steps:
+      - name: Verify x86_64 host
+        shell: pwsh
+        # https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor
+        run: |
+          if ((Get-WmiObject win32_processor).Architecture -ne 9) {
+            echo "Not running on an x86_64 machine, cannot build for x86_64-unknown-windows-msvc!"
+            exit 1
+          }
       - name: Setup Windows
         uses: llvm/actions/setup-windows@llvmorg-17.0.6
         with:
